name: CI/CD pfe MyBookStore
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -Dmaven.test.skip=true install
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn test
  push-to-docker-registry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker login
        env:
          PASSWORD: ${{ secrets.PASSWORD }}
          USER: ${{ secrets.USER }}
        run: docker login -u $USER -p $PASSWORD
      - name: Build the Docker image
        run: docker build -t mai77/spring-pfe .
      - name: Push the Docker image
        run: docker push mai77/spring-pfe:latest